Repository rit-sse/WebsiteTheSSEquel, pull requests merged in 2023-11, with the labels that each got.

#91 Dev/governing docs styling
  next/app/about/constitution/page.tsx
  next/app/about/primary-officers-policy/page.tsx
  next/app/globals.scss
  next/components/nav/Navbar.tsx
Labels: front-end, tailwind

#87 Dev/golinks routing
  next/lib/README.md
  next/lib/middlewares/golinks.ts
  next/lib/utils.ts
  next/middleware.ts
Labels: front-end, next.js

#85 Dev/get involved
  next/app/about/committees/CommitteeSlot.tsx
  next/app/about/committees/CommitteeSlotData.ts
  next/app/about/committees/page.tsx
  next/app/about/get-involved/InvolvementSlot.tsx
  next/app/about/get-involved/InvolvementSlotData.ts
  next/app/about/get-involved/page.tsx
  next/components/ZCard.tsx
  next/components/ZCardContainer.tsx
  next/package-lock.json
  next/types/ZCardContent.ts
Labels: front-end

#63 Leadership Page Integration
  next/app/about/leadership/OfficerCard.tsx
  next/app/about/leadership/page.tsx
  next/app/about/leadership/team.ts
  next/app/layout.tsx
  next/components/common/Icons.tsx
  next/prisma/migrations/20231014215953_/migration.sql
  next/prisma/migrations/20231020191726_auth_and_go_links/migration.sql
Labels: react, front-end, tailwind

#92 Dev/auth (User Login) #33
  README.md
  documentation/EnvironmentSetup.md
  next/.gitignore
  next/app/Providers.tsx
  next/app/api/auth/[...nextauth]/route.ts
  next/app/globals.scss
  next/app/layout.tsx
  next/components/common/Button.tsx
  next/components/common/HoverBoldButton.tsx
  next/components/nav/AuthButton.tsx
  next/components/nav/NavItem.tsx
  next/components/nav/Navbar.tsx
  next/package-lock.json
  next/package.json
  next/prisma/schema.prisma
Labels: front-end, auth.js
